name: CI

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.12.2
        uses: actions/setup-node@v4
        with:
          node-version: "20.12.2"
          cache: "yarn"
          cache-dependency-path: "**/.yarn/releases/*.cjs"

      - name: Cache Yarn
        uses: actions/cache@v3
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Build
        run: yarn build

      - name: Run tests
        run: yarn test --passWithNoTests
